#ifndef WSPACE_AFFINE_OPERATORS_HPP_EF93F1B3C76D467F83722959FB9057B8
#define WSPACE_AFFINE_OPERATORS_HPP_EF93F1B3C76D467F83722959FB9057B8

#include "point.hpp"
#include "vector.hpp"

namespace wspace {

WSPACE_ARRAY_DECLARE_GENERIC_ARITHMETIC_ASSIGNMENT_OPERATOR(+=, Point, Vector)
WSPACE_ARRAY_DECLARE_GENERIC_BINARY_ARITHMETIC_OPERATOR(+, Point, Vector, Point)

WSPACE_ARRAY_DECLARE_GENERIC_ARITHMETIC_ASSIGNMENT_OPERATOR(-=, Point, Vector)
WSPACE_ARRAY_DECLARE_GENERIC_BINARY_ARITHMETIC_OPERATOR(-, Point, Vector, Point)

WSPACE_ARRAY_DECLARE_GENERIC_BINARY_ARITHMETIC_OPERATOR(-, Point, Point, Vector)

} // namespace wspace

// ============================================================
// Implementation
// ============================================================

namespace wspace {

WSPACE_ARRAY_DEFINE_GENERIC_ARITHMETIC_ASSIGNMENT_OPERATOR(+=, Point, Vector)
WSPACE_ARRAY_DEFINE_GENERIC_BINARY_ARITHMETIC_OPERATOR(+, Point, Vector, Point)

WSPACE_ARRAY_DEFINE_GENERIC_ARITHMETIC_ASSIGNMENT_OPERATOR(-=, Point, Vector)
WSPACE_ARRAY_DEFINE_GENERIC_BINARY_ARITHMETIC_OPERATOR(-, Point, Vector, Point)

WSPACE_ARRAY_DEFINE_GENERIC_BINARY_ARITHMETIC_OPERATOR(-, Point, Point, Vector)

} // namespace wspace

#endif // WSPACE_AFFINE_OPERATORS_HPP_EF93F1B3C76D467F83722959FB9057B8
